### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [mmariscalg/jenkins-test-failure-magnifier#1]
Si ves este issue en la web de zube.io es que estamos viendo el mismo proyecto. Contesta con un comentario para saberlo.

**Comment by mmariscalg** [comment]
Hola Patxi. Todo correcto

**Comment by gortazar** [comment]
Ok. Algunas cuestiones primero:
- ¿Estás familiarizado con git?
- ¿Entiendes o intuyes cómo funciona zube.io desde el punto de vista de la planificación del proyecto?

**Comment by mmariscalg** [comment]
Con Git no estoy familiarizado.

Con zube.io creo que si, aunque no he trabajado con ello si que usamos durante un tiempo Trello en la empresa y algún otro sistema de gestión similar como GanttProject en alguna asignatura de la ingeniería.

**Comment by mmariscalg** [comment]
Hola patxi.

Me he descargado Jenkins para Windows, he instalado el plugin de Github y he creado el proyecto, enlazándolo con el de Github.

No se si es un buen primer paso, pero quería cacharrear un poco.

**Comment by gortazar** [comment]
Perfecto, voy a dar de alta algunas tareas más concretas para que veas lo que hay que hacer. Pero familiarizarte un poco con Jenkins es un primer paso necesario.

**Comment by mmariscalg** [comment]
Ok perfecto.

Mientras tanto buscaré tutoriales y demás para ir empapándome bien.

**Comment by gortazar** [comment]
Ok. Esta semana verás aparecer algunos issues con tareas para ir arrancando. Serán al principio cosas para irte familiarizando con las tecnologías.

**Comment by mmariscalg** [comment]
Ok Patxi, perfecto.
